version: '3.8'
services:
  crm_db:

    image: pgvector/pgvector:pg16
    container_name: agent_postgres_vector
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./pgdata_vector:/var/lib/postgresql/data
      - ./init_vector_db.sql:/docker-entrypoint-initdb.d/init_db.sql